### ISSUE TITLE
Cannot get the regex for command line switches to work. Documentation lacks examples.

### ISSUE THREAD

**Issue by therealjessesanford** [logentries/docker-logentries#38]
The readme shows examples for use in javascript but does not show how to use the "REGEX" for the switches passed to the containers entrypoint as the docker command. I am trying to get the following to work to limit the logs to a single container based on a unique image name and nothing seems to work. No matter how I format the regex value the agent still seems to send logs from all running containers to logentries. I have tried:

-t $LOGENTRIES_TOKEN -j --privileged --no-stats --matchByImage='/.*uniq_img_name.*/'
-t $LOGENTRIES_TOKEN -j --privileged --no-stats --matchByImage='.*uniq_img_name.*'
-t $LOGENTRIES_TOKEN -j --privileged --no-stats --matchByImage='*uniq_img_name*'

-t $LOGENTRIES_TOKEN -j --privileged --no-stats --matchByImage '/.*uniq_img_name.*/'
-t $LOGENTRIES_TOKEN -j --privileged --no-stats --matchByImage '.*uniq_img_name.*'
-t $LOGENTRIES_TOKEN -j --privileged --no-stats --matchByImage '*uniq_img_name*'

I know the last one is not valid regex but i tried anyways incase it's using some nonstandard wildcard syntax. Can you please show us some examples of how this is supposed to be formatted?

**Comment by KieranOBrien-R7** [comment]
Hi,

This relates to the base we are using which also has an issue with the matchByX REGEXP

https://github.com/mcollina/docker-allcontainers/issues/5

**Comment by AdrianRossouw** [comment]
as far as i can determine, the individual log entries for the matched images are no longer sent to logentries (ie: their stdout).

However, the docker events (container up/down, etc) are still sent for all containers.

the format is

`-t $LOGENTRIES_TOKEN -j -a host=`uname -n` --no-stats --matchByImage='.*uniq_img_name.*'`

**Comment by jtrh** [comment]
Here's an example of regex usage that I used in a Docker Cloud _stack file_:

```yaml
my-service-logs:
  # Filter logs so that they only consider a specific application,
  # using a regex that matches:
  # serviceName-containerNumber.stackName.containerId
  #
  # Example: myService-42.myStack.abcd56
  command: "--secure --matchByName 'myService-\\d+\\.myStack\\.\\w+'"
```

Verified to work with b39cb0641b521cf3bcdc77d0912684ec07723ab9.
